name: Latest YouTube videos
on:
  schedule:
    # Runs every Sunday at 9:00 AM JST (0:00 UTC)
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme-with-youtube:
    name: Update README with latest YouTube videos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update README with latest YouTube videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCmMnuEXRsrNNcW4bVeeTI8A"
          max_post_count: 5
          template: "- [$title]($url)"
